spring:
  application:
    name: booking
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: ${PASTE_YOUR_NAME_HERE}
    password: ${PASTE_YOUR_PASSWORD_HERE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true
#  cache:
#    type: redis
#    redis:
#      host: localhost
#      port: 6379

server:
  port: 8080

app:
  properties:
    time-threshold: 15
    booking-percent: 0.15
